version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: security_db
      MYSQL_ROOT_PASSWORD: Nokidding123456
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/security_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nokidding123456
    depends_on:
      - mysql-db
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
