apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
#    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
#      tier: database
  template:
    metadata:
      labels:
        app: mysql
#        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
#            - name: DATABASE_URL
#              value: "jdbc:mysql://mysql-db:3306/security_db"
            - name: MYSQL_ROOT_PASSWORD
              value: Nokidding123456
            - name: MYSQL_DATABASE
              value: security_db
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
#    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

