apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cors-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/huynguyen1908/jwt.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
